import Head from 'next/head'
import styles from '@/styles/Gift.module.css'
import ImageRotator from 'lib/ImageRotator'

const imageInfo = {
  initial: '/kujibiki.png',
  hit: '/kuji_atari.png',
  miss: '/kuji_hazure.png',
}

const images = Array(4).fill(imageInfo);

export default function Gift() {
  return (
    <>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <section>
          <h2 className={styles.h2text}>一枚選択</h2>
          <div>
            {images.map((image, index) => (
              <ImageRotator
                key={index}
                initialImage={image.initial}
                resultImages={{
                  hit: image.hit,
                  miss: image.miss,
                }}
                width={300}
                height={300}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  )
}
