import Head from 'next/head'
import styles from '@/styles/Gift.module.css'
import ImageRotator from 'lib/ImageRotator'

export default function Gift() {
  return (
    <>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <section>
          <h2 className={styles.h2text}>カードを一枚タップしてください</h2>
          <div>
          <ImageRotator
            initialImage="/kujibiki.png"
            resultImages={{
              hit: '/kuji_atari.png',
              miss: '/kuji_hazure.png',
            }}
            width={300}
            height={300}
          />
          </div>
        </section>
      </main>
    </>
  )
}
