import Head from 'next/head'
import styles from '@/styles/Gift.module.css'
import ImageRotator from 'lib/ImageRotator'

const image = {
  initial: '/kujibiki.png',
  hit: '/kuji_atari.png',
  miss: '/kuji_hazure.png',
}

export default function Gift() {
  return (
    <>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <section>
          <h2>Hello</h2>
          <div>
            <ImageRotator
              initialImage={image.initial}
              resultImages={{
                hit: image.hit,
                miss: image.miss,
              }}
              width={300}
              height={300}
            />
          </div>
        </section>
      </main>
    </>
  )
}
